# Generated by Django 4.1 on 2022-12-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
