# Generated by Django 4.1 on 2022-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
